version: 2
updates:
  # Enable version updates for .NET
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "dpalfery"
    assignees:
      - "dpalfery"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "dotnet"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "dpalfery"
    assignees:
      - "dpalfery"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    ignore:
      # Avoid automatic upgrades of our .NET version
      - dependency-name: "actions/setup-dotnet"
        update-types: ["version-update:semver-major"]
