version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hotshot_sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Hotshot123!
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data:
    name: hotshot_sqlserver_data 