<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RollForward>LatestMajor</RollForward>
    <NoWarn>xUnit1051</NoWarn>
    <UserSecretsId>a562df9b-74fa-48b9-adfc-379cdc5868a7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="FluentMigrator" Version="8.0.1" />
    <PackageReference Include="FluentMigrator.Runner.SqlServer" Version="8.0.1" />
    <PackageReference Include="FluentMigrator.Runner" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.30" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\0-Base\HotshotLogistics.Core\HotshotLogistics.Core.csproj" />
    <ProjectReference Include="..\..\..\1-Presentation\HotshotLogistics.Api\HotshotLogistics.Api.csproj" />
    <ProjectReference Include="..\..\..\2-Application\HotshotLogistics.Application\HotshotLogistics.Application.csproj" />
    <ProjectReference Include="..\..\..\3-Domain\HotshotLogistics.Contracts\HotshotLogistics.Contracts.csproj" />
    <ProjectReference Include="..\..\..\3-Domain\HotshotLogistics.Domain\HotshotLogistics.Domain.csproj" />
    <ProjectReference Include="..\..\..\4-Persistence\HotshotLogistics.Data\HotshotLogistics.Data.csproj" />
    <ProjectReference Include="..\..\..\4-Persistence\MigrationRunner\MigrationRunner.csproj" />
  </ItemGroup>

</Project>
