name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Deploy"]
    types:
      - completed
    branches: [development]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    # Only run if the terraform plan workflow was successful or if it's a manual trigger
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DAVIDS_AZURE_SUB }}
      - name: Terraform Init
        run: terraform -chdir=7-Deployment/Azure-deploy/solution/HotshotLogistics init
      - name: Terraform Apply
        run: terraform -chdir=7-Deployment/Azure-deploy/solution/HotshotLogistics apply -auto-approve -var-file=../../environments/${{ github.event.inputs.environment || 'dev' }}/hotshot.tfvars 